#include "test_server_helper.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <thread>
#include <chrono>
#include <filesystem>
#include <cstdio>
#include <cstring>

#ifdef _WIN32
#include <winsock2.h>
#pragma comment(lib, "ws2_32.lib")
#endif

TestServerHelper::TestServerHelper(const Options& opts) : m_opts(opts) {}

TestServerHelper::~TestServerHelper() {
    stop();
}

bool TestServerHelper::setup() {
    killProcessOnPort(m_opts.clientPort);
    namespace fs = std::filesystem;
    try {
        fs::create_directories(m_opts.workDir);
    } catch (...) {
        std::cerr << "无法创建工作目录: " << m_opts.workDir << "\n";
        return false;
    }
    if (!createTestDataFiles()) return false;
    if (!createServerConfig()) return false;
    return true;
}

void TestServerHelper::killProcessOnPort(int port) {
#ifdef _WIN32
    std::string cmd = "netstat -ano | findstr :" + std::to_string(port) + " | findstr LISTENING";
    FILE* pipe = popen(cmd.c_str(), "r");
    if (!pipe) return;
    char buf[256];
    while (fgets(buf, sizeof(buf), pipe)) {
        std::string line(buf);
        size_t lastNonSpace = line.find_last_not_of(" \t\r\n");
        if (lastNonSpace == std::string::npos) continue;
        size_t lastSpace = line.rfind(' ', lastNonSpace);
        if (lastSpace == std::string::npos) continue;
        std::string pidStr = line.substr(lastSpace + 1, lastNonSpace - lastSpace);
        int pid = std::stoi(pidStr);
        HANDLE h = OpenProcess(PROCESS_TERMINATE, FALSE, pid);
        if (h) {
            TerminateProcess(h, 1);
            WaitForSingleObject(h, 1000);
            CloseHandle(h);
            std::cout << "  已终止残留进程 PID: " << pid << "\n";
        }
    }
    pclose(pipe);
#endif
}

bool TestServerHelper::createTestDataFiles() {
    // 用户数据: 与 TestRunner 一致
    std::string usersContent =
        "V=1\n"
        "2|admin|admin123|System Admin|000-0000|Head Office|0\n"
        "0|alice|pwd123|Alice|111-2222|Addr1|200.0\n"
        "1|bob|pwd456|Bob|222-3333|Addr2|100.0\n"
        "0|charlie|pwd789|Charlie|333-4444|Addr3|300.0\n";
    std::string usersPath = m_opts.workDir + "/users.dat";
    std::ofstream uf(usersPath);
    if (!uf) { std::cerr << "无法创建: " << usersPath << "\n"; return false; }
    uf << usersContent;
    uf.close();

    std::string parcelsPath = m_opts.workDir + "/parcels.dat";
    std::ofstream pf(parcelsPath);
    if (!pf) { std::cerr << "无法创建: " << parcelsPath << "\n"; return false; }
    pf << "V=1\n";
    pf.close();

    std::string configPath = m_opts.workDir + "/config.dat";
    std::ofstream cf(configPath);
    if (!cf) { std::cerr << "无法创建: " << configPath << "\n"; return false; }
    cf << "V=1\n5000.0\n";
    cf.close();

    return true;
}

bool TestServerHelper::createServerConfig() {
    std::string configContent =
        "# Auto-generated by test helper\n"
        "ip=0.0.0.0\n"
        "port=8888\n"
        "log_level=FATAL\n"
        "auto_assign_courier=false\n"
        "max_idle_time=180\n"
        "user_file=users.dat\n"
        "parcel_file=parcels.dat\n"
        "config_file=config.dat\n";
    std::string configPath = m_opts.workDir + "/server_config.txt";
    std::ofstream cf(configPath);
    if (!cf) { std::cerr << "无法创建: " << configPath << "\n"; return false; }
    cf << configContent;
    cf.close();
    return true;
}

bool TestServerHelper::start() {
#ifdef _WIN32
    std::string fullPath = std::filesystem::absolute(m_opts.serverPath).string();
    std::string workDirAbs = std::filesystem::absolute(m_opts.workDir).string();

    if (!std::filesystem::exists(fullPath)) {
        std::cerr << "服务器程序不存在: " << fullPath << "\n";
        return false;
    }

    STARTUPINFOA si = { sizeof(si) };
    ZeroMemory(&m_procInfo, sizeof(m_procInfo));

    if (!CreateProcessA(
            fullPath.c_str(), NULL,
            NULL, NULL, FALSE,
            CREATE_NO_WINDOW,
            NULL, workDirAbs.c_str(),
            &si, &m_procInfo)) {
        std::cerr << "CreateProcess failed (" << GetLastError() << "): " << fullPath << "\n";
        return false;
    }
    m_serverRunning = true;
    std::cout << "服务器进程已启动 (PID: " << m_procInfo.dwProcessId << ")\n";
    return true;
#else
    std::cerr << "仅支持 Windows\n";
    return false;
#endif
}

void TestServerHelper::stop() {
#ifdef _WIN32
    if (m_serverRunning && m_procInfo.hProcess) {
        DWORD exitCode = 0;
        if (GetExitCodeProcess(m_procInfo.hProcess, &exitCode) && exitCode == STILL_ACTIVE) {
            TerminateProcess(m_procInfo.hProcess, 0);
            WaitForSingleObject(m_procInfo.hProcess, 3000);
        }
        CloseHandle(m_procInfo.hProcess);
        CloseHandle(m_procInfo.hThread);
        ZeroMemory(&m_procInfo, sizeof(m_procInfo));
        m_serverRunning = false;
        std::cout << "服务器进程已停止\n";
    }
#endif
}

bool TestServerHelper::waitForReady(int maxRetries, int delayMs) {
    std::cout << "等待服务器就绪...\n";
    for (int i = 0; i < maxRetries; ++i) {
#ifdef _WIN32
        WSADATA wsaData;
        bool wsaStarted = (WSAStartup(MAKEWORD(2, 2), &wsaData) == 0);
        SOCKET s = socket(AF_INET, SOCK_STREAM, 0);
        if (s != INVALID_SOCKET) {
            sockaddr_in addr;
            addr.sin_family = AF_INET;
            addr.sin_port = htons(m_opts.clientPort);
            addr.sin_addr.s_addr = inet_addr(m_opts.clientIp.c_str());
            if (connect(s, (sockaddr*)&addr, sizeof(addr)) != SOCKET_ERROR) {
                closesocket(s);
                if (wsaStarted) WSACleanup();
                std::cout << "服务器就绪 (尝试 " << (i + 1) << " 次)\n";
                return true;
            }
            closesocket(s);
        }
        if (wsaStarted) WSACleanup();
#endif
        std::this_thread::sleep_for(std::chrono::milliseconds(delayMs));
    }
    std::cerr << "服务器未能就绪 (超时)\n";
    return false;
}

void TestServerHelper::cleanup() {
    namespace fs = std::filesystem;
    try {
        if (fs::exists(m_opts.workDir)) {
            fs::remove_all(m_opts.workDir);
        }
    } catch (...) {}
}
